Github templates added
shapelets/khiva-matlab pull request #3
Opened 2018-06-13 17:12 UTC by dcuestam

2018-06-18 13:48 UTC, avilchess commented on CONTRIBUTING.md
> +
Delete one blank line

2018-06-21 16:43 UTC, otorreno commented on README.md
> +### Contributing
2 '#'

2018-06-21 16:44 UTC, otorreno requested changes
Take a look at the comments

2018-06-21 16:48 UTC, otorreno approved these changes
LGTM

2018-06-21 17:10 UTC, merged